name: Step 1, Resolve duplicate issues

# This step triggers after 0-start.yml
# This step sets STEP to 2
# This step closes <details id=1> and opens <details id=2>

# This will run every time we update or close the issue
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows

on:
  workflow_dispatch:
  issue_comment:
    types: [created, edited]

permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:

  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: get_step
        run: echo "::set-output name=current_step::$(cat ./.github/script/STEP)"
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
  
  on_duplicate_issue_closed:
    name: Check if duplicate issue is marked as duplicate
    needs: get_current_step
    
    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently 1 (see update-step.sh)
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: ${{ github.repository_owner != 'TBD-organization' }} 
      && needs.get_current_step.outputs.current_step == 1 }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      - name: Dump GitHub comment context
        id: github_comment_step
        run: echo '${{ toJSON(github.event.comment) }}'
        
      - name: Dump GitHub issue context
        id: github_issue_step
        run: echo '${{ toJSON(github.event.issue) }}'
        
      - name: Check if commented issue is closed and marked as duplicate
        if: ${{ contains(github.event.comment.body, 'Duplicate of') && (github.event.issue.state == 'closed')}}
        run: echo 'Duplicate issue closed'

      # Update README to close <details id=1>
      # and open <details id=2>
      # and set STEP to '2'
      - name: Update to step 2
        run: ./.github/script/update-step.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FROM_STEP: 1
          TO_STEP: 2
          BRANCH_NAME: main
