name: Step 2, Configure Your Action

# This step listens for the learner pushing a commit to `main`
# This step sets STEP to 3
# This step closes <details id=2> and opens <details id=3>

# This will run every time we push a commit to `main`
# Reference https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches:
      - main
  
permissions:
  # Need `contents: read` to checkout the repository
  # Need `contents: write` to update the step metadata
  contents: write

jobs:

  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: get_step
        run: echo "::set-output name=current_step::$(cat ./.github/script/STEP)"
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}
      
  on_check_action_file_added:
    name: Check if the action.yml file was added
    needs: get_current_step
    
    # We will only run this action when:
    # 1. This repository isn't the template repository
    # 2. The STEP is currently 2
    # Reference https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 2 }}

    # We'll run Ubuntu for performance instead of Mac or Windows
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Let's get all the branches

      - name: Dump GitHub comment context
        id: github_comment_step
        run: echo '${{ toJSON(github.event) }}'
        
      # Check if NPM package.json exists in the expected location
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: ".github/actions/joke-action/action.yml"

      # Update README to close <details id=2>
      # and open <details id=3>
      # and set STEP to '3'
      - name: Update to step 3
        if: steps.check_files.outputs.files_exists == 'true'
        uses: skills/action-update-step@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 2
          to_step: 3
