name: Step 3, Create Metadata File

# This step listens for the learner pushing a commit to `main`.
# This workflow updates from step 3 to step 4.

# This will run every time we push a commit to `main`.
# Reference: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows
on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  # Need `contents: read` to checkout the repository.
  # Need `contents: write` to update the step metadata.
  contents: write

env:
  EXPECTED_METADATA: outputs

jobs:
  # Get the current step to only run the main job when the learner is on the same step.
  get_current_step:
    name: Check current step number
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - id: get_step
        run: |
          echo "current_step=$(cat ./.github/steps/-step.txt)" >> $GITHUB_OUTPUT
    outputs:
      current_step: ${{ steps.get_step.outputs.current_step }}

  on_action_file_contains_expected_metadata:
    name: Check if the action.yml file contains the expected metadata
    needs: get_current_step

    # We will only run this action when:
    # 1. This repository isn't the template repository.
    # 2. The step is currently 3.
    # Reference: https://docs.github.com/en/actions/learn-github-actions/contexts
    # Reference: https://docs.github.com/en/actions/learn-github-actions/expressions
    if: >-
      ${{ !github.event.repository.is_template
          && needs.get_current_step.outputs.current_step == 3 }}

    # We'll run Ubuntu for performance instead of Mac or Windows.
    runs-on: ubuntu-latest

    steps:
      # We'll need to check out the repository so that we can edit the README.
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0 # Let's get all the branches.

      - name: Dump GitHub comment context
        id: github_comment_step
        env:
          COMMENT_CONTEXT: ${{ toJson(github.event) }}
        run: echo "$COMMENT_CONTEXT"

      # Check if action.yml file contains metadata.
      - name: Read action file contents
        id: read_action_yml_file
        uses: andstor/file-reader-action@v1
        with:
          path: ".github/actions/joke-action/action.yml"

      # Update README to from step 3 to step 4.
      - name: Update to step 4
        if: (contains(steps.read_action_yml_file.outputs.contents, ${{ env.EXPECTED_METADATA }})
        uses: skills/action-update-step@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from_step: 3
          to_step: 4
